real_nav_goals:
  marker:
    position:
      x: -1.740
      y: 0.203
      z: 0.020
    orientation:
      x: 0.001
      y: -0.003
      z: 0.999
      w: -0.093
  atdoor:
    position:
      x: -0.931
      y: 0.079
      z: 0.021
    orientation:
      x: -0.00
      y: 0.002
      z: -0.723
      w: 0.691
  postdoor:
    position:
      x: -0.943
      y: -0.801
      z: 0.025
    orientation:
      x: -0.004
      y: -0.003
      z: -0.725
      w: 0.688
  bin:
    position:
      x: -0.499
      y: -0.991
      z: 0.037
    orientation:
      x: -0.003
      y: -0.005
      z: -0.575
      w: 0.818
  home:
    position:
      x: 0
      y: 0
      z: 0
    orientation:
      x: 0.003
      y: -0.012
      z: -0.000
      w: 1.000
  table:
    position:
      x: -1.740
      y: 0.203
      z: 0.020
    orientation:
      x: 0.002
      y: -0.003
      z: 0.818
      w: 0.573

    