real_nav_goals:
  marker:
    position:
      x: -1.494
      y: -0.105
      z: 0.023
    orientation:
      x: -0.00
      y: 0.02
      z: -0.99
      w: 0.00
  atdoor:
    position:
      x: -0.793
      y: -0.199
      z: 0.0
    orientation:
      x: -6.55
      y: 0.00
      z: -0.721
      w: 0.702
  postdoor:
    position:
      x: -0.804
      y: -1.039
      z: 0.0
    orientation:
      x: -0.0
      y: -0.0
      z: -0.705
      w: 0.709
  bin:
    position:
      x: -0.382
      y: -1.442
      z: 0.0
    orientation:
      x: -0.00
      y: -0.00
      z: -0.418
      w: 0.908
  home:
    position:
      x: -0.09
      y: 0.10
      z: 0.02
    orientation:
      x: 0.0
      y: -0.0
      z: -0.646
      w: 0.99
    