real_nav_goals:
  marker:
    position:
      x: -0.604
      y: -1.580
      z: 0.178
    orientation:
      x: -0.003
      y: 0.001
      z: -0.586
      w: 0.811
  atdoor:
    position:
      x: -0.509
      y: -0.923
      z: 0.180
    orientation:
      x: -0.002
      y: 0.001
      z: 0.111
      w: 0.994
  postdoor:
    position:
      x: 0.223
      y: -0.741
      z: 0.184
    orientation:
      x: -0.001
      y: -0.005
      z: 0.117
      w: 0.993
  bin:
    position:
      x: 0.366
      y: -0.528
      z: 0.004
    orientation:
      x: -0.000
      y: -0.005
      z: 0.223
      w: 0.975
  home:
    position:
      x: -0.923
      y: -0.246
      z: 0.009
    orientation:
      x: 0.005
      y: -0.003
      z: 0.714
      w: 0.700
  table:
    position:
      x: -0.604
      y: -1.580
      z: 0.178
    orientation:
      x: 0.003
      y: -0.002
      z: 0.996
      w: -0.087