real_nav_goals:
  marker:
    position:
      x: -0.604
      y: -1.580
      z: 0.178
    orientation:
      x: -0.003
      y: 0.001
      z: -0.586
      w: 0.811
  atdoor:
    position:
      x: -0.509
      y: -0.923
      z: 0.180
    orientation:
      x: -0.002
      y: 0.001
      z: 0.111
      w: 0.994
  postdoor:
    position:
      x: 0.223
      y: -0.741
      z: 0.184
    orientation:
      x: -0.001
      y: -0.005
      z: 0.117
      w: 0.993
  bin:
    position:
      x: 0.417
      y: -0.440
      z: 0.187
    orientation:
      x: 0.001
      y: -0.006
      z: 0.201
      w: 0.979
  home:
    position:
      x: -0.890
      y: -0.070
      z: 0.177
    orientation:
      x: 0.005
      y: -0.004
      z: 0.694
      w: 0.720
  table:
    position:
      x: -0.604
      y: -1.580
      z: 0.178
    orientation:
      x: 0.003
      y: -0.002
      z: 0.996
      w: -0.087