real_nav_goals:
  generic_object:
    position:
      x: -1.277
      y: -0.115
      z: 0.020
    orientation:
      x: 0.001
      y: -0.002
      z: 1.000
      w: -0.017
  atdoor:
    position:
      x: -0.728
      y: -0.355
      z: 0.083
    orientation:
      x: -0.000
      y: 0.002
      z: -0.731
      w: 0.683
  postdoor:
    position:
      x: -0.835
      y: -1.079
      z: 0.087
    orientation:
      x: -0.005
      y: -0.002
      z: -0.723
      w: 0.691
  bin:
    position:
      x: -0.350
      y: -1.369
      z: 0.015
    orientation:
      x: -0.003
      y: -0.005
      z: -0.747
      w: 0.664
  home:
    position:
      x: -0.069
      y: -0.107
      z: 0.105
    orientation:
      x: 0.001
      y: -0.006
      z: -0.009
      w: 1.000
  table:
    position:
      x: -1.309
      y: -0.162
      z: 0.098
    orientation:
      x: 0.001
      y: -0.004
      z: 0.714
      w: 0.700