from typing import Union, Tuple
import rospy
import numpy as np
from nav_msgs.msg import OccupancyGrid, MapMetaData


class OccupancyGridMerger:
    def __init__(self):
        self.topic = '/locobot/move_base/global_costmap/costmap'
        self.subscriber = rospy.Subscriber(self.topic, OccupancyGrid, self.callback)
        self.costmap_grid = None
        self.grid_info = None

        self.og_subscriber = rospy.Subscriber('/locobot/rtabmap/grid_map', OccupancyGrid, self.occupancy_grid_callback)

        self.occupancy_grid = None

    def occupancy_grid_callback(self, data: OccupancyGrid):
        # Extract the grid data from the message
        width = data.info.width
        height = data.info.height
        grid_data = np.array(data.data).reshape(height, width)
        
        self.occupancy_grid = grid_data
        self.og_subscriber.unregister()


    def callback(self, data: OccupancyGrid):
        width = data.info.width
        height = data.info.height
        grid_data = np.array(data.data).reshape(height, width)
        
        self.costmap_grid = grid_data
        self.grid_info = data.info


    def deflate_costmap(self):
        """
        Replaces all occurrences of 99 in the costmap with the corresponding elements 
        from the occupancy grid.

        This is needed because the costmap is "inflated"; in addition to marking obstacles with 
        the value 100, it marks an area around the obstacles with the value 99, to indicate cells
        where the robot could collide with an obstacle due to its footprint (see documentation at
        https://wiki.ros.org/costmap_2d#Inflation). This is useful for navigation, but we really
        only are interested in the actual occupancy grid. We remove the inflated values so that we
        end up with a costmap that is more similar to the occupancy grid. 

        Returns:
            The new costmap.
        """
        deflated = self.costmap_grid.copy() # Create a copy to avoid modifying the original array
        
        # Find the indices where costmap is equal to 99
        indices = np.where(deflated == 99)

        # Replace the 99 values in the costmap copy with the corresponding values from the occupancy grid
        deflated[indices] = self.occupancy_grid[indices]
        
        return deflated

    

    def replace_values(self):
        """(position, orientation) = self.tf_listener.lookupTransform('/map', 'locobot/base_link', rospy.Time(0))
            x, y = position[0], position[1]  # Extract the x, y coordinates of the robot's position

        Replaces values in the occupancy grid that are not marked occupied with
        50 if the corresponding value in the deflated costmap is 100.

        This is used to mark novelty obstructions in the occupancy grid with a different value,
        to indicate that the "obstruction" isn't known to be an actual obstacle. The MDP learning
        process can use this to decide it can try passing through those cells, while knowing not to
        try to pass through cells that are marked as occupied (100) in the occupancy grid.

        Returns:
        A new numpy array with the replaced values.
        """

        # Based on code generated by Gemini

        np.savetxt("costmap_inflated.out.txt", self.costmap_grid, fmt='%3d')
        # np.savetxt(sys.stdout, self.occupancy_grid, fmt='%3d')
        deflated_costmap = self.deflate_costmap()
        np.savetxt("costmap_deflated.out.txt", deflated_costmap, fmt='%3d')

        replaced = self.occupancy_grid.copy() # Create a copy to avoid modifying the original array
        og_mask = (replaced >= 0) & (replaced < 100) # Create a boolean mask for values in range [0, 100) [1.3.3, 1.2.1].
        cm_mask = deflated_costmap == 100
        mask = og_mask & cm_mask # Combine the masks to get the indices where both conditions are met

        replaced[mask] = 50 # Use the mask to replace values in the occupancy grid with 50 where the costmap is 100
        
        return replaced

    def get_occupancy_grid(self) -> Tuple[Union[np.ndarray, None], Union[MapMetaData, None]]:
        """
        Returns the occupancy grid and its metadata, with the current costmap's obstacle data added.

        Returns:
        """

        if self.occupancy_grid is None:
            rospy.loginfo("Waiting for occupancy grid data...")
            return None, None

        
        if self.costmap_grid is None:
            rospy.loginfo("Waiting for costmap data...")
            return None, None
        
        replaced_costmap = self.replace_values()

        self.subscriber.unregister()
        self.subscriber = rospy.Subscriber(self.topic, OccupancyGrid, self.callback)
        return replaced_costmap, self.grid_info

if __name__ == "__main__":
    import sys
    rospy.init_node('test_occupancy_grid', anonymous=True)

    merger = OccupancyGridMerger()

    while True:
        grid, info = merger.get_occupancy_grid()
        if grid is not None:
            break

    grid = grid.reshape((info.height, info.width))

    np.savetxt(sys.stdout, grid, fmt='%3d')
